### ISSUE TITLE
Need updation of the plugin as per new albert version 0.18

### ISSUE THREAD

**Issue by prashantjain25** [DenverCoder1/unit-converter-albert-ext#1]
With new updates to version 0.18.10 the unit-converter is not loading in plugins section, therefore it might require update.

**Comment by DenverCoder1** [comment]
Let me know if it's working for you now.

Check the new instructions added to the readme.

**Comment by DenverCoder1** [comment]
It seems that Albert 0.18 isn't really liking plugins with no prefix trigger so much. While it is working as before currently, it's possible the synopsis may change in a future version.

**Comment by prashantjain25** [comment]
converter seems working now only when calculator is not working as from below extensions:-
https://github.com/albertlauncher/python

Is there currency conversion also in plan? units could be better for integration.

**Comment by DenverCoder1** [comment]
There was a currency converter already in albert (by Manuel) but it seems it's not up to date with 0.18.

https://github.com/albertlauncher/python/blob/master/.archive/currency_converter/__init__.py

I suppose I could merge the two plugins into one.

**Comment by prashantjain25** [comment]
Also seems calculator and converter are clashing, calculator stops working when converter is enabled.

**Comment by DenverCoder1** [comment]
Yeah, I think I'll need to give a default prefix, for example "convert ..."

**Comment by DenverCoder1** [comment]
Do you think it would be better to default to "uc " or "convert "

"convert" is more natural, but "uc" is a bit more convenient since it's short

**Comment by prashantjain25** [comment]
yes shorthand notation would be appealing to everyone like "cnv"

**Comment by DenverCoder1** [comment]
I added currency support. You can configure the trigger in the settings to be `cnv` or whatever you like.
