### ISSUE TITLE
Small units are rounded to zero

### ISSUE THREAD

**Issue by prashantjain25** [DenverCoder1/unit-converter-albert-ext#3]
Should there be decimal places upto non zeros 2-3 digits, if result is not absolute zero? or there could be a better solution like rounding off decimals upto user inputted limit
![Screenshot from 2023-01-10 22-45-51](https://user-images.githubusercontent.com/5137282/211618719-016dc14b-e1d8-41f1-9b9c-f02277559080.png)

**Comment by DenverCoder1** [comment]
Yeah, it seems the round and truncate may be too aggressive when it comes to small numbers.

Maybe it could be a configurable option in the config.json?

**Comment by prashantjain25** [comment]
Working as expected
