### ISSUE TITLE
Add currency conversion

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/unit-converter-albert-ext#5]
There was a currency converter already in albert (by Manuel) but it seems it's not up to date with 0.18.

[`albertlauncher/python@master/.archive/currency_converter/__init__.py`](https://github.com/albertlauncher/python/blob/master/.archive/currency_converter/__init__.py?rgh-link-date=2023-01-10T17%3A08%3A02Z)

I suppose the two plugins could be merged into one.

First suggested in #1

**Comment by prashantjain25** [comment]
working as expected
